version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: pg_billing
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_password
      POSTGRES_USER: postgres
      POSTGRES_DB: billing_db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5

  billing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      ENVIRONMENT: local
    depends_on:
      postgres:
          condition: service_healthy
